import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

/**
 * Browser favicon — matches the in-app Logo component.
 * Auto-generated by Next.js from this file.
 */
export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #53d4ff 0%, #7c4dff 55%, #f5b94f 100%)",
          borderRadius: "8px",
        }}
      >
        <div
          style={{
            width: 0,
            height: 0,
            borderLeft: "10px solid white",
            borderTop: "7px solid transparent",
            borderBottom: "7px solid transparent",
            marginLeft: "3px",
          }}
        />
      </div>
    ),
    { ...size },
  );
}
